#test again this version of Node.js

environment:
matrix:
#node.js
-nodejs_version "16"

#Install script
install:
-ps: install-Product node $env:nodejs_version

-npm install

test_script:
-node --version
-npm --version

-npm test


build:off